import "./globals.css";

export const metadata = {
  title: "Thet Oo Aung",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        <header>This is the header!</header>
        {children}
        <footer>This is the footer!</footer>
      </body>
    </html>
  );
}
