import NavBar from "./components/ui/NavBar";
import "./globals.css";

export const metadata = {
  title: "Thet Oo Aung",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar></NavBar>
        <div className="container mx-auto">{children}</div>

        {/* <footer>This is the footer!</footer> */}
      </body>
    </html>
  );
}
